name: Plantilla para que los issues que se abran sigan las buenas prácticas
description: Usa esta plantilla cuando crees un issue para registrar un problema en el proyecto que haya que solucionar.

body:
  - type: markdown
    attributes:
      value: |
        # Plantilla para para que los issues que se abran sigan las buenas prácticas
        **Buena Práctica:** Un buen Issue representa siempre un problema **Claro**, **Conciso** y **Accionable** y nunca expresa una solución.
        Por favor, sigue las instrucciones de cada campo para facilitar la clasificación y el inicio rápido del trabajo.

  - type: textarea
    id: descripcion-problema
    attributes:
      label: Descripción detallada del problema
      description: "Describe de la forma más clara y concisa posible el problema."
      placeholder: "Escriba aquí"
    validations:
      required: true
    
  - type: checkboxes
    id: comprobaciones
    attributes:
      label: Lista de comprobación
      description: Verifica que has revisado estos puntos antes de crear el issue.
      options:
        - label: Mi issue describe claramente un problema o necesidad (el QUÉ), sin proponer una solución (el CÓMO).
        - label: He incluido toda la información necesaria para entender y reproducir el problema
        - label: He mencionado cualquier otro Issue o Pull Request que esté relacionado con este.
        - label: He asignado un milestone y las etiquetas adecuadas a este Issue.
        - label: He buscado en los issues existentes y he comprobado que este no está duplicado.
    validations:
      required: true
